### PR TITLE
Add an option to change go toolkit version for windows builder image

### PR DESCRIPTION
**Pull request by angrykirc**
Add an option to change go toolkit version for windows builder image.
This is needed to make a Windows 7 compatible builds.

### CODE REVIEW

**Review by dennwc — APPROVED** [review]

**Comment by angrykirc** [comment]
Something is wrong, the pipeline gets stuck at "Entering fakeroot environment..." message for more than 30 minutes.
But if I try to build the image locally on my Debian laptop, everything is OK and it builds in 9mins, strange...

**Comment by dennwc** [comment]
Maybe some GH glitch? Try restarting tomorrow.

**Comment by angrykirc** [comment]
Lol, the base runner image was seemingly the culprit.
@dennwc If you are OK with the base image change (it's frequently updated anyway), I'm merging it.

**Review by dennwc — APPROVED** [review]
LGTM!

**Pull request merged**
